"use client";

import './globals.css';

import { metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ClientRootLayout } from "./client-layout";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Vtech Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {
  return (
    <ClientRootLayout>
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
    </ClientRootLayout>
  )
}

export default RootLayout;

